#!/usr/bin/env bash

# Read each line of /etc/passwd
while IFS=: read -r username _ uid _ home _; do
    # Print username, user id, and home directory path
    echo ": $username"
    echo "$uid"
    echo "$home"
    echo
done < /etc/passwd

