#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
string="Best School"
st="Hi"
counter=1
while [[ $counter -le 10 ]];
do
  echo "$string"
  if [[ $counter -eq 9 ]]
     then
      echo "$st"
     fi
     ((counter+=1))
done
