#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
string="Best School"
st="bad luck"
st1="good luck"
counter=1
while [[ $counter -le 10 ]];
do
  if [[ $counter == 4 ]]
     then
      echo "$st"
  elif [[ $counter == 8 ]]
     then
      echo "$st1"
  else
	  echo "$string" 
     fi
     ((counter+=1))
done
