#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
string="Best School"
st="bad luck"
st1="good luck"
counter=1
while [[ $counter -le 10 ]];
do
  echo "$string"
  if [[ $counter -eq 4 ]]
     then
      echo "$st"
  elif [[ $counter -eq 8 ]]
     then
      echo "$st1"
     fi
     ((counter+=1))
done
