#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#!/bin/bash

hour=0
minute=1

while [ $hour -le 12 ];do
	if [ $hour == 0 ]; then
	echo "Hour: $hour"
else
    minute=1
    while [ $minute -le 60 ]; do
	if [ $minute -eq 60 ]; then
	  echo "Hour: $hour"
	else
          echo "$minute"
	fi

        ((minute++))
    done
	fi
    ((hour++))
done

