#!/usr/bin/env bash
# A Script print the content of a current directory
for file in *; do
 if [ ! -f "$file" -o $file == .* ]; then
    continue
    fi
  name=$(echo "$file" | cut -d'-' -f2-)
  echo "$name"
 done
