#!/usr/bin/env bash
# configure Nginx to serve your page from the route /airbnb-onepage/
server {
    listen 80;
    server_name _; 
    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header X-Served-By "481601-web-01";
    }
}
