#!/usr/bin/env bash
# This is a shell script that acept argument and runs the whoami command under that user using sudo
if [ -z "$1" ]; then
	echo "Usage: $0 <username>"
	exit 1
fi
username=$1
sudo -u "$username" whoami
