#!/usr/bin/env bash
#This programme is about making nginx a user
if ! id -u nginx > /dev/null 2>&1; then
	sudo useradd -r nginx
fi
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default
sudo mkdir -p /var/www/html
sudo chown -R nginx:nginx /var/www/html
sudo service nginx restart 
sudo service nginx status
